### ISSUE TITLE
默认镜像地址无法下载

### ISSUE THREAD

**Issue by vinnyzhaowenyu** [loggie-io/installation#11]
安装到 Kuberentes 中时，报错镜像无法下载。

建议，将镜像推送到 hub.docker.com

例如：
```
hub.docker.com/loggie/loggie:latest
```

报错信息：
```
      state:
        waiting:
          message: Back-off pulling image "hub.c.163.com/qingzhou/loggie:latest"
          reason: ImagePullBackOff
```
